name = "reveal-hugo"
license = "MIT"
licenselink = "https://github.com/dzello/reveal-hugo/blob/master/LICENSE"
homepage = "https://reveal-hugo.dzello.com/"
tags = ["presentation", "revealjs"]
features = ["presentation"]

[author]
name = "Govind, ZH"
homepage = "https://github.com/gaocn"

[original]
name = "reveal.js"
homepage = "https://revealjs.com"
repo = "https://github.com/hakimel/reveal.js/"